### ISSUE TITLE
moving ffplayout-engine into this project

### ISSUE THREAD

**Issue by lavvy** [ffplayout/ffplayout-gui#1]
I think you are doing an awesome job with this project. I may not know what inspired the structure of this project but i think you could roll all the parts in one project and make a dockerfile so that it can enable some of us to easily contribute to the work.
I think moving the ffplayout engine to the root of this project and dumping the folder in www folder of a lampstack should get the whole thing up and running

**Comment by jb-alvarado** [comment]
I split engine and gui, because not everybody needs the gui. That are to different projects, and as you see the engine has more attention at the moment.
