### ISSUE TITLE
new gui for ffplayout

### ISSUE THREAD

**Issue by lavvy** [ffplayout/ffplayout-gui#2]
Somehow i am thinking the gui app is pretty much a calender scheduler script like https://ui.toast.com/tui-calendar that can be able to represent the playlist.json .
Then an upload script like dropzone.js to add the playlists.json and media contents.
Infact looks like https://github.com/nhn has a bunch of tools to take a look

**Comment by jb-alvarado** [comment]
Yes sometimes I was thinking on a real program scheduler to, but I was not sure if this would not be a bit overkill. For a complete scheduler app I would make more sense to use a database (mysql for example). But this is more work.

The calendar app is nice, there is also the js project fullcalendar - is also a nice one.

We can collect all ideas and then see what we can realize. I think the soonest time I can start is in 2-3 month. 

Would you be willing to take a part? What is more your area: backend, or frontend? A colleague from me will make a nice layout sketch, what can be realize later in bootstrap.

**Comment by lavvy** [comment]
oh wow, its an honor unfortunately i will not consider myself a very good programmer . I never went to school for it , i basically learnt on my own without rules. I think i am more of an influencer than a programmer. 
Fullcalender is very cool. Its javascript, i dont see how it would be an overkill . Secondly a calendar feature is a necessity that is must be present no matter what technology used.

**Comment by jb-alvarado** [comment]
I'm closing here, because v2 is in progress...
