### ISSUE TITLE
Nginx installation error

### ISSUE THREAD

**Issue by wturra** [ffplayout/ffplayout-gui#20]
**At the end of installation:**

add your ssl config to /etc/nginx/sites-available/ffplayout.conf

... etc etc ...

ll /etc/nginx/sites-available/ffplayout.conf
ls: cannot access '/etc/nginx/sites-available/ffplayout.conf': No such file or directory

**NOTE:** Seems that when you select option "Y" at nginx installation step, it doesn't work.

**More info:**

install and setup nginx:

... etc etc ...

Do you wish to install nginx? (Y/n) :$ Y

... etc etc ...

Superuser created successfully.
Created symlink /etc/systemd/system/multi-user.target.wants/ffplayout-api.service → /etc/systemd/system/ffplayout-api.service.
cp: cannot create regular file '/etc/nginx/sites-available/': No such file or directory
ln: target '/etc/nginx/sites-enabled/' is not a directory: No such file or directory
sed: can't read /etc/nginx/sites-available/ffplayout.conf: No such file or directory
sed: can't read /etc/nginx/sites-available/ffplayout.conf: No such file or directory

....

**NOTE:** Tested on: AWS EC2 - Ubuntu 18 server AMI - t2.medium

Regards,
Waldino

**Comment by jb-alvarado** [comment]
Thank you for reporting, can you please check, if nginx was installed, and it the folder: **/etc/nginx/sites-available/** exists?

**Comment by wturra** [comment]
nginx binary wasn't installed, and "/etc/nginx/sites-available/" folder do not exist.

Regards.

**Comment by wturra** [comment]
The workaround is to previously install nginx using apt, but It's just a workaround. I suspect is not the way you want.

Regards

**Comment by jb-alvarado** [comment]
Hm, that sounds more that by accident you select no nginx to install. The install script needs nginx to be installed, even when is not selected. I have to change this.

**Comment by wturra** [comment]
No, already tested 2 times. I checked it to be sure I was typing fine.

Regards.

**Comment by jb-alvarado** [comment]
Hm, that is interesting! I made some rearrangements and try it again in a fresh debian vm, and there it install nginx.

**Comment by jb-alvarado** [comment]
Was nodejs and the other tools are installed? Maybe this is related to the AWS instance.

**Comment by wturra** [comment]
It was working before fix #19.

**Comment by wturra** [comment]
> Was nodejs and the other tools are installed? Maybe this is related to the AWS instance.

Yes, nodejs was installed. I am trying the code always on the same template machine.  This error started after fix #19.

Regards.

**Comment by jb-alvarado** [comment]
I have rearrange some things in the inttall script, maybe you want to give it a try again. If you just need it to run, I can assist you to, whit manually installation.

**Comment by wturra** [comment]
Done !
