### ISSUE TITLE
build ffmpeg-git failed...

### ISSUE THREAD

**Issue by simplecode678** [ffplayout/ffplayout-gui#21]
Hi,
What may be the issue for : 
build ffmpeg-git failed...
delete the source folder under '/opt/ffmpeg-build/build' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window

FYI install done with
"compile and install (nonfree) ffmpeg:" y
"install and setup nginx:" y
"install and srs rtmp/hls server:" y
"install ffplayout-engine:" y

Thanks

**Comment by simplecode678** [comment]
I have "hit enter for continue it"
But then after install i can not play video : The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by jb-alvarado** [comment]
Hi,
at the moment libsrt is broken, so you need to change `--enable-libsrt` to `#--enable-libsrt` in install.sh. 

Or if you want to compile ffmpeg manually:

- cd in **cd /opt/ffmpeg-build/**
- edit **build_config.txt** and change line  `--enable-libsrt` to `#--enable-libsrt` 
- delete folder: **build/ffmpeg-git**
- run build script: **./compile-ffmpeg.sh**
- when is done: `cp local/bin/ff* /usr/local/bin/`

**Comment by simplecode678** [comment]
Change done https://raw.githubusercontent.com/simplecode678/ffplayout-gui/master/install.sh
But after : 
build libuuid-1.0.3 failed...
delete the source folder under '/opt/ffmpeg-build/build' and start again,
or if you know there is no dependences hit enter for continue it
first close the batch window, then the shell window

If hit enter next buils will make error as well

**Comment by jb-alvarado** [comment]
I just run the script to, and it was working... Maybe sourceforge was done for a second, then you could run the compiler script again, like I say before.

Which system you are using?

**Comment by simplecode678** [comment]
Sorry was done on centos7, install done with script on centos 8
But i can't still preview mp4 "The media could not be loaded, either because the server or network failed or because the format is not supported."
At first i thought that "build ffmpeg-git failed..." was the problem

**Comment by jb-alvarado** [comment]
Sorry, I forgot a symlink and the video source link was not optimal.

For manually fixing:
- go to **/var/www/ffplayout**
- `git update`
- `ln -s "/opt/ffplayout/media" /var/www/ffplayout/ffplayout/frontend/static/` # the source path which you are choice
- `cd /var/www/ffplayout/ffplayout/frontend`
- `sudo -H -u nginx bash -c 'npm run build'`

**Comment by simplecode678** [comment]
Sorry... sudo -H -u nginx bash -c 'npm run build' gives:
FATAL  EACCES: permission denied, mkdir '/var/www/ffplayout/ffplayout/frontend/node_modules/.cache/nuxt/build-lock-2f5c6735'

✖ Nuxt Fatal Error                                                                     │
   │                                                                                          │
   │   Error: EACCES: permission denied, mkdir                                                │
   │   '/var/www/ffplayout/ffplayout/frontend/node_modules/.cache/nuxt/build-lock-2f5c6735'   │
   │                                                                                          │
   ╰──────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffplayout@2.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffplayout@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jb-alvarado** [comment]
- `chown nginx. -R /var/www/ffplayout/`
- `cd /var/www/ffplayout/ffplayout/frontend`
- `sudo -H -u nginx bash -c 'npm run build'`

**Comment by simplecode678** [comment]
Thanks ! I have seen that you have done a new install.sh
I will check software in details and make new install for your latest install
