### ISSUE TITLE
HLS output

### ISSUE THREAD

**Issue by wturra** [ffplayout/ffplayout-gui#22]
Hi, would be possible to output directly to HLS format ?..for example:

-c:v libx264 -crf 21 -preset veryfast -g 25 -sc_threshold 0 -c:a aac -b:a 128k -ac 2 -f hls -hls_time 4 -hls_playlist_type event  stream.m3u8

With this mod, It wouldn't be necessary srs for the case of streaming using  HLS.

I tried to change "post_ffmpeg_param" without success. I'm also digging into /opt/ffplayout-engine/ffplayout.py to know how much effort I should put to make this work.

Regards.

**Comment by jb-alvarado** [comment]
Hi, yes this is possible and is also integrated already in [dev branch](https://github.com/ffplayout/ffplayout-engine/tree/dev).
Maybe the next days I will merge it in master branch, but if you want you can test it now already.

**Comment by wturra** [comment]
Great ! I will give it a try today.

Regards.
