### ISSUE TITLE
Not playing

### ISSUE THREAD

**Issue by RoxyBoxxy** [ffplayout/ffplayout-gui#23]
its not playing the playlist when i click play it will not do anything 
![image](https://user-images.githubusercontent.com/8870878/88714690-0e244d80-d115-11ea-8a54-5a8bcdffb01f.png)

**Comment by RoxyBoxxy** [comment]
Error i am getting 
`Jul 28 20:41:22 ns351552 systemd[1]: Started python and ffmpeg based playout.
Jul 28 20:41:22 ns351552 python[6301]: Traceback (most recent call last):
Jul 28 20:41:22 ns351552 python[6301]:   File "/opt/ffplayout-engine/ffplayout.py", line 25, in 
Jul 28 20:41:22 ns351552 python[6301]:     from ffplayout.folder import GetSourceFromFolder, MediaStore, MediaWatcher
Jul 28 20:41:22 ns351552 python[6301]:   File "/opt/ffplayout-engine/ffplayout/folder.py", line 28, in 
Jul 28 20:41:22 ns351552 python[6301]:     from .filters import build_filtergraph
Jul 28 20:41:22 ns351552 python[6301]:   File "/opt/ffplayout-engine/ffplayout/filters.py", line 23, in 
Jul 28 20:41:22 ns351552 python[6301]:     from .utils import _pre_comp
Jul 28 20:41:22 ns351552 python[6301]:   File "/opt/ffplayout-engine/ffplayout/utils.py", line 226, in 
Jul 28 20:41:22 ns351552 python[6301]:     load_config()
Jul 28 20:41:22 ns351552 python[6301]:   File "/opt/ffplayout-engine/ffplayout/utils.py", line 181, in load_config
Jul 28 20:41:22 ns351552 python[6301]:     _pre_comp.add_logo = cfg['pre_compress']['add_logo']
Jul 28 20:41:22 ns351552 python[6301]: KeyError: 'pre_compress'
Jul 28 20:41:23 ns351552 systemd[1]: ffplayout-engine.service: Main process exited, code=exited, status=1/FAILURE
Jul 28 20:41:23 ns351552 systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Jul 28 20:41:24 ns351552 systemd[1]: ffplayout-engine.service: Service hold-off time over, scheduling restart.
Jul 28 20:41:24 ns351552 systemd[1]: ffplayout-engine.service: Scheduled restart job, restart counter is at 5.
Jul 28 20:41:24 ns351552 systemd[1]: Stopped python and ffmpeg based playout.
Jul 28 20:41:24 ns351552 systemd[1]: ffplayout-engine.service: Start request repeated too quickly.
Jul 28 20:41:24 ns351552 systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Jul 28 20:41:24 ns351552 systemd[1]: Failed to start python and ffmpeg based playout.`

**Comment by jb-alvarado** [comment]
Please use the newest ffplayout-engine version from master, inclusive the yaml config file.

```
 28 20:41:22 ns351552 python[6301]:     _pre_comp.add_logo = cfg['pre_compress']['add_logo']
```
Here it says the an old parameter is in use, which are not existing anymore.

How come the start/stop buttons are moved to top? This I can not reproduce - which browser are you using?

**Comment by RoxyBoxxy** [comment]
I am using Chrome

**Comment by jb-alvarado** [comment]
Yes, in my chrome it is also out of place. I will fix it.

**Comment by RoxyBoxxy** [comment]
So i tried with the master git for the engine and still getting errors 
Warning: The unit file, source configuration file or drop-ins of ffplayout-engine.service changed on disk. Run 'systemctl daem
● ffplayout-engine.service - python and ffmpeg based playout
   Loaded: loaded (/etc/systemd/system/ffplayout-engine.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-07-29 17:12:47 CEST; 36s ago
  Process: 25502 ExecStart=/opt/ffplayout-engine/venv/bin/python /opt/ffplayout-engine/ffplayout.py (code=exited, status=1/FAI
 Main PID: 25502 (code=exited, status=1/FAILURE)

Jul 29 17:12:47 raznet.dev systemd[1]: ffplayout-engine.service: Service hold-off time over, scheduling restart.
Jul 29 17:12:47 raznet.dev systemd[1]: ffplayout-engine.service: Scheduled restart job, restart counter is at 5.
Jul 29 17:12:47 raznet.dev systemd[1]: Stopped python and ffmpeg based playout.
Jul 29 17:12:47 raznet.dev systemd[1]: ffplayout-engine.service: Start request repeated too quickly.
Jul 29 17:12:47 raznet.dev systemd[1]: ffplayout-engine.service: Failed with result 'exit-code'.
Jul 29 17:12:47 raznet.dev systemd[1]: Failed to start python and ffmpeg based playout.
lines 1-13/13 (END)

**Comment by RoxyBoxxy** [comment]
Fixed, i had to change 2 lines of code in /opt/ffplayout-engine/ffplayout.py to point to /opt/ffplayout-engine/ffplayout/output
