### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ssdeol84** [ffplayout/ffplayout-gui#24]
Hi friends I'm not able to login

Getting error 404

I don't want to use SSL

So I've just opened the gui without SSL it opened but gives error when we put user name and password.

Plz let me know what's the probelm.

**Comment by jb-alvarado** [comment]
Hi,
I run again a test on a fresh debian 10 VM, and there everything work normal.

- Have you add a domain name? A IP address works to
- Have you add a user name and password?
- When yes, can you login to django admin page?: http://domain/admin
- Which system/version are you using?
- What says the browser console?

**Comment by ssdeol84** [comment]
Thanks for quick response I'm using CentOS 8.

Yes I've setup username root
And password Tiger@84
And set domain name : my public ip.

And I'm using Google Chrome on same network.

But it's giving me error ..it's not accepting user password. Can u check through TeamViewer.

**Comment by ssdeol84** [comment]
Thanks by domain/admin 

I've setup new password now its opening

Thanks

**Comment by ssdeol84** [comment]
Can we run multiplayer or multi instance ??

**Comment by jb-alvarado** [comment]
Is on my todo, but I don't think I make it in the next months. At the moment I would recommend to use multiple VMs.

**Comment by ssdeol84** [comment]
Multi vm is a good option but it requires more hardware resources... multiple instance is better option...

I would eagerly waiting for ur next version for multiple instances
