### ISSUE TITLE
preview clip don't work

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-gui#26]
Hi,
I point out that, due to your recent changes to the path of the source playlist file .... "add .../ opt / ffplayout" the "play preview button" is no longer working (it still points only to / media /clip and not on /opt/ffplayout/media/clip)
I await feedback, thanks.

<img width="1162" alt="d1" src="https://user-images.githubusercontent.com/59960414/91282757-a3048000-e781-11ea-9cd7-5b122c950df3.PNG">
<img width="481" alt="d2" src="https://user-images.githubusercontent.com/59960414/91282767-a5ff7080-e781-11ea-8271-c46b1c258cb5.PNG">

**Comment by jb-alvarado** [comment]
You need to run:

```
ln -s /opt/ffplayout/media /var/www/ffplayout/ffplayout/frontend/static/
```

and then:
```
cd /var/www/ffplayout/ffplayout/frontend && npm run build
```

**Comment by chicco64** [comment]
does not work with the indicated change, I have to repeat a new clean install

**Comment by jb-alvarado** [comment]
Maybe `/var/www/ffplayout/ffplayout/frontend/static/` need sub folders `opt/ffplayout` and then:

```
ln -s /opt/ffplayout/media /var/www/ffplayout/ffplayout/frontend/static/opt/ffplayout/
```

**Comment by chicco64** [comment]
just confirm to me that your project has now been updated on git and I proceed with a fresh install, many thanks

**Comment by jb-alvarado** [comment]
normally you don't have to make a fresh clean install, a `git pull` and `npm run build` for the GUI is enough.

Soon I will write a update function in the install script.

**Comment by chicco64** [comment]
I still did a clean new install but now I get the following new errors, and it is no longer possible to stream
<img width="1242" alt="e1" src="https://user-images.githubusercontent.com/59960414/91301648-2e3f3f00-e79d-11ea-939c-9c279f7c72af.PNG">
<img width="1228" alt="e2" src="https://user-images.githubusercontent.com/59960414/91301659-31d2c600-e79d-11ea-8b09-a4337e61610f.PNG">
<img width="1395" alt="e3" src="https://user-images.githubusercontent.com/59960414/91301668-34cdb680-e79d-11ea-9224-67daec8e1660.PNG">

**Comment by jb-alvarado** [comment]
When the playlist is to short of course ffplayout is not able to stream.
