### ISSUE TITLE
message sending failed

### ISSUE THREAD

**Issue by chicco64** [ffplayout/ffplayout-gui#27]
Hi, 
I can't send messages, ffplayout is active in playlist mode.
please see attachments

<img width="1065" alt="f1" src="https://user-images.githubusercontent.com/59960414/91354311-7766b180-e7e4-11ea-9dd6-7997f3892e21.PNG">
<img width="980" alt="f2" src="https://user-images.githubusercontent.com/59960414/91354320-7b92cf00-e7e4-11ea-97c7-5a785b2bd4fb.PNG">

**Comment by jb-alvarado** [comment]
Can you try this again, with open browser development console and see which error message you see there? Is there also any log entry?

**Comment by jb-alvarado** [comment]
Are you using CentOS? When is a debian like system you just need to enable the text filter in config.

**Comment by chicco64** [comment]
I used "debian10"
can you specify where I need to enable "the text filter" in config (?)
thanks
<img width="1262" alt="s1" src="https://user-images.githubusercontent.com/59960414/91437939-89873500-e862-11ea-8cd6-221276a40665.PNG">
<img width="1233" alt="s2" src="https://user-images.githubusercontent.com/59960414/91437947-8c822580-e862-11ea-967b-651007632475.PNG">
<img width="1262" alt="s3" src="https://user-images.githubusercontent.com/59960414/91437955-8ee47f80-e862-11ea-893c-7999e3bdb3f9.PNG">
<img width="1251" alt="s4" src="https://user-images.githubusercontent.com/59960414/91437965-9146d980-e862-11ea-88cb-ac9b70d93414.PNG">
<img width="1202" alt="s5" src="https://user-images.githubusercontent.com/59960414/91437983-960b8d80-e862-11ea-9a84-8efde60078c4.PNG">
<img width="1260" alt="s6" src="https://user-images.githubusercontent.com/59960414/91437991-999f1480-e862-11ea-9457-83057d942a97.PNG">
<img width="1220" alt="s7" src="https://user-images.githubusercontent.com/59960414/91437998-9c016e80-e862-11ea-979a-47f91bc88989.PNG">

**Comment by jb-alvarado** [comment]
On your last picture is: **add_text**

**Comment by chicco64** [comment]
now the "message" application works perfectly, thanks
