### ISSUE TITLE
Yaml requirements

### ISSUE THREAD

**Issue by pkExec** [ffplayout/ffplayout-gui#3]
This commit: https://github.com/ffplayout/ffplayout-gui/commit/fd1a0920ef3441dc155442d2f56400862dc315d6 added support for yml configuration file.

However, the implementation requires:
- PHP < 7.3 (since yaml module is not implemented for PHP 7.3)
- PHP development version, with custom configuration to enable yaml module. 
This is something that most shared hosts won't be able to provide, only custom VPS servers.

I suggest:
a) mentioning the above requirements in the front page
b) revert to good old ini file, for both ffplayout-engine and ffplayout-gui when time permits.

**Comment by jb-alvarado** [comment]
Thank you for the suggestion!

Yes I should mention the requirements in from page. But the installation is very easy. When yaml support is not installed, you can do it in Debian wit `apt install php-yaml`, on other systems like fedora it is also present.

The reason why I change to yaml is, that in the future I will change to GUI to python/Django and nuxtjs. In would like to have the opportunity to change the config in the GUI, and it is a bit easier to serialize yaml, then the ini format.

**Comment by pkExec** [comment]
FYI, because installing yaml was not supported by my hosting provider, I ended up including this: https://github.com/mustangostang/spyc, and changing yamlReader.php to 
`function get_yaml() {
    return Spyc::YAMLLoad("/etc/ffplayout/ffplayout.yml", 0);
}`
I think it's a much more portable solution (especially since the native yaml module isn't available for newer PHP versions).

**Comment by jb-alvarado** [comment]
Thank you for the hint! If you want, you can make a pull request. But I'm working on v2, there I use different frameworks. The first release will hopefully around the end of this week, or next week.

**Comment by jb-alvarado** [comment]
For getting a small taste: https://github.com/ffplayout/ffplayout-gui/tree/v2.0.0-dev
